### ISSUE TITLE
Pre Alpha 1.3 Checklist

### ISSUE THREAD

**Issue by lucasdamianjohnson** [Divine-Star-Software/DivineVoxelEngine#12]
This is a checklist for Alpha 1.3
- [x]  Add a dimensions property. So, those regions/chunks can be stored in dimensions.
- [x]  Add ways to work with dimensions for queues and world generation.
- [x]  Make water flow run light updates when flowing and removing.
- [x]  Make sure that the 45-degree angle UV textures work when flipped for smooth lighting on the water mesh.
- [x] Condense chunk data into a single array buffer. 
- [x] Separate voxel ids and light values into separate parts of the buffer. 
- [x] Create a `ChunkReader` object that can be used in all threads to read chunk data.
- [x] Create an array buffer world columns with data related to its states and so on.
- [x] Make sure that the voxel engine can run headless on a server.
- [x] Make sure that multi-threaded world generation works. 
- [x] Update saving data to work with the new type of chunk data.
- [x] Implement chunk states as well as a header part of the array buffer. 
- [ ] Fix server example.

**Comment by lucasdamianjohnson** [comment]
I am closing th is out now. Going to release the update anyway.
