### ISSUE TITLE
Pre Alpha 1.2 Release Checklist - The Shape & Data Update

### ISSUE THREAD

**Issue by lucasdamianjohnson** [Divine-Star-Software/DivineVoxelEngine#9]
- [x] Fix the issue with textures not actually being aligned correctly.  Might have to switch the UV or change the face. 
- [x] Make a way for different voxel shapes to cull faces. For instance, have a half-box call its bottom face only if it is directly on top of a box.
- [x] Fix the problem with the voxel state data not being properly set and passed. 
- [x] Upgrade the `ShapeBuilder` to have more options and transform vectors for creating many different types of shapes. 
- [x] Add a "Face state" vertex data attribute for all meshes to control shaders. For instance, if a fluid meshes face is flipped that state should be set and the texture should be set to flow in the correct direction. 
- [x] Also, correct the flora shader to create the "wind" effect only if the proper face state is set. Also have different modes for something like leaves vs vines and so on. 
- [x] Add "tile entities" or a way to connect voxels to "rich data" 
   - Will need to create a new type of region just for rich states. 
- [X] Add cull face and AO overrides for shapes
- [x] Fix the AO by checking to flip the states.
- [x] Add a 360 rotation so that textures can be flipped. 
- [x] Add new types of shapes. 
    - [X] Vines aka Panel
    - [x] Stairs
         - [x] Bottom states
         - [x] Top States
         - [x] Connected Bottom States
         - [x] Connected Top States 
- [x] Add a way to generate a chunk in the constructor thread so chunks and generated in parallel. 
- [x] Implement the shape state data. 
- [x] Add a way to flip a texture. Must account for when the texture is flipped. 
- [x] Implement a helper UV function to generate the correct UV data. 
- [x] Add an overlay texture mode and add it to the chunk templates and the generated mesh data. 
- [x] I will have to make an overlay texture for each mesh type. 
- [x] Remove "per-region voxel palettes". 
- [x] Add an easy way to create a custom voxel manager to pass to `WorldMatrix`. 
- [x] Implement an optional `physics` property for voxels. 
- [x] Create a way to save a region and a way to load in a region.

**Comment by lucasdamianjohnson** [comment]
## Changes
---
List of things that I will need to update the wiki for. Will also have to update the wiki for 1.1. 

So, I changed the voxel data type definition. 
It is now:
```ts
type VoxelData = {
 name: string;
 shapeId: string;
 id: string;
 substance: VoxelSubstanceType;
 states?: string[];
 lightSource?: boolean;
 lightValue?: number;
};
```
This is a breaking change from other versions. But now voxel states actually work. So, when you add a state to the states array it will be passed to the voxel `process` function so you can do different things with it. 

Also realized that the `defaultState` literally did nothing so I just removed it.

**Comment by lucasdamianjohnson** [comment]
Alpha 1.2 is out now.
